# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex2', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='user_liked',
            field=models.ManyToManyField(related_name='liked_quotes', to='ex2.User'),
        ),
    ]
